create table if not exists public.study_snapshots (
  id bigint generated by default as identity primary key,
  owner_id text not null,
  app text not null,
  payload jsonb not null,
  reason text,
  updated_at timestamptz not null default now()
);

create unique index if not exists study_snapshots_owner_app_unique
  on public.study_snapshots (owner_id, app);

alter table public.study_snapshots enable row level security;

drop policy if exists "read own snapshot" on public.study_snapshots;
create policy "read own snapshot"
  on public.study_snapshots
  for select
  to anon
  using (true);

drop policy if exists "write own snapshot" on public.study_snapshots;
create policy "write own snapshot"
  on public.study_snapshots
  for all
  to anon
  using (true)
  with check (true);
